rootProject.name = "talker"
include("talker-bukkit")
include("talker-common")
include("talker-velocity")
include("talker-bungee")
include("talker-api")
include("talker-server")
include("talker-client")
include("talker-test")
include("talker-api-server")
include("talker-api-client")
include("talker-minecraft")
include("talker-test-bukkit")
include("talker-test-velocity")
include("talker-folia")
include("talker-kook")
